---
title: "Kategoriske data og logistiske regressioner"
teaching: 10
exercises: 5
questions:
- "FIXME"
objectives:
- "FIXME"
keypoints:
- "FIXME"
source: Rmd
math: yes
---

```{r, include = FALSE}
source("../bin/chunk-options.R")
knitr_fig_path("07-")
# source("../bin/download_data.R")
library(tidyverse)
library(patchwork)
```

# R-eksempler fra modul 5

## overlevelsesanalyse (survival analysis)


Analyse af "tid til event". Eg "tid til død", men kan i praksis bruges til alle 
former for "tid til x"

En af årsagerne til komplikationer er "censur" på data - situationer hvor man
"taber" observationer. Eksempelvis at man mister kontakten til personen 
der studeres. 

Og det kan overlevelsesanalyser kunne håndtere.


Logistisk regression ville kunne sige noget om sandsynligheden for begivenheden.
Men ikke hvornår. Det kan overlevelsesanalysen.

funktionen der bruges er coxph(), samt Surv(TIME, EVENT), der bruges til at 
angive tidselementet i datasættet, og det udvald vi kigger efter. 

coxph(Surv(TIME, EVENT) ~prediktor1 + prediktor2 + osv, data = datasæt)

summary giver koefficienter og p-værdier som vanligt.

Kigger man på overlevelsesfunktionen direkte, anvendes kaplan-meier estimation.






## Incidens

antaly nye tilfælde af noget man ønsker at følge.

## Poisson regression

Her undersøges incidense. Dvs bare en tællevariabel







{% include links.md %}
